#!/bin/bash
mv -f Boat_noisy_sobel_10_denoised_binary_edge_map_threshold_10.raw Boat_noisy_sobel_10_denoised_binary_edge_map_threshold_10.gray
convert -size 321x481 -depth 8 Boat_noisy_sobel_10_denoised_binary_edge_map_threshold_10.gray Boat_noisy_sobel_10_denoised_binary_edge_map_threshold_10.png
mv -f Boat_noisy_sobel_10_denoised_binary_edge_map_threshold_clean_10.raw Boat_noisy_sobel_10_denoised_binary_edge_map_threshold_clean_10.gray
convert -size 321x481 -depth 8 Boat_noisy_sobel_10_denoised_binary_edge_map_threshold_clean_10.gray Boat_noisy_sobel_10_denoised_binary_edge_map_threshold_clean_10.png
mv -f Boat_noisy_sobel_10_denoised_differentiated.raw Boat_noisy_sobel_10_denoised_differentiated.gray
convert -size 321x481 -depth 8 Boat_noisy_sobel_10_denoised_differentiated.gray Boat_noisy_sobel_10_denoised_differentiated.png
mv -f Boat_noisy_sobel_10_denoised_edge_map_no_threshold.raw Boat_noisy_sobel_10_denoised_edge_map_no_threshold.gray
convert -size 321x481 -depth 8 Boat_noisy_sobel_10_denoised_edge_map_no_threshold.gray Boat_noisy_sobel_10_denoised_edge_map_no_threshold.png
mv -f Boat_noisy_sobel_10_denoised.raw Boat_noisy_sobel_10_denoised.gray
convert -size 321x481 -depth 8 Boat_noisy_sobel_10_denoised.gray Boat_noisy_sobel_10_denoised.png
mv -f Boat_noisy_sobel_10_gray.raw Boat_noisy_sobel_10_gray.gray
convert -size 321x481 -depth 8 Boat_noisy_sobel_10_gray.gray Boat_noisy_sobel_10_gray.png
mv -f Boat_noisy_sobel_15_binary_edge_map_threshold_15.raw Boat_noisy_sobel_15_binary_edge_map_threshold_15.gray
convert -size 321x481 -depth 8 Boat_noisy_sobel_15_binary_edge_map_threshold_15.gray Boat_noisy_sobel_15_binary_edge_map_threshold_15.png
mv -f Boat_noisy_sobel_15_binary_edge_map_threshold_clean_15.raw Boat_noisy_sobel_15_binary_edge_map_threshold_clean_15.gray
convert -size 321x481 -depth 8 Boat_noisy_sobel_15_binary_edge_map_threshold_clean_15.gray Boat_noisy_sobel_15_binary_edge_map_threshold_clean_15.png
mv -f Boat_noisy_sobel_15_denoised_binary_edge_map_threshold_15.raw Boat_noisy_sobel_15_denoised_binary_edge_map_threshold_15.gray
convert -size 321x481 -depth 8 Boat_noisy_sobel_15_denoised_binary_edge_map_threshold_15.gray Boat_noisy_sobel_15_denoised_binary_edge_map_threshold_15.png
mv -f Boat_noisy_sobel_15_denoised_binary_edge_map_threshold_clean_15.raw Boat_noisy_sobel_15_denoised_binary_edge_map_threshold_clean_15.gray
convert -size 321x481 -depth 8 Boat_noisy_sobel_15_denoised_binary_edge_map_threshold_clean_15.gray Boat_noisy_sobel_15_denoised_binary_edge_map_threshold_clean_15.png
mv -f Boat_noisy_sobel_15_denoised_differentiated.raw Boat_noisy_sobel_15_denoised_differentiated.gray
convert -size 321x481 -depth 8 Boat_noisy_sobel_15_denoised_differentiated.gray Boat_noisy_sobel_15_denoised_differentiated.png
mv -f Boat_noisy_sobel_15_denoised_edge_map_no_threshold.raw Boat_noisy_sobel_15_denoised_edge_map_no_threshold.gray
convert -size 321x481 -depth 8 Boat_noisy_sobel_15_denoised_edge_map_no_threshold.gray Boat_noisy_sobel_15_denoised_edge_map_no_threshold.png
mv -f Boat_noisy_sobel_15_denoised.raw Boat_noisy_sobel_15_denoised.gray
convert -size 321x481 -depth 8 Boat_noisy_sobel_15_denoised.gray Boat_noisy_sobel_15_denoised.png
mv -f Boat_noisy_sobel_15_differentiated.raw Boat_noisy_sobel_15_differentiated.gray
convert -size 321x481 -depth 8 Boat_noisy_sobel_15_differentiated.gray Boat_noisy_sobel_15_differentiated.png
mv -f Boat_noisy_sobel_15_edge_map_no_threshold.raw Boat_noisy_sobel_15_edge_map_no_threshold.gray
convert -size 321x481 -depth 8 Boat_noisy_sobel_15_edge_map_no_threshold.gray Boat_noisy_sobel_15_edge_map_no_threshold.png
mv -f Boat_noisy_sobel_15_gray.raw Boat_noisy_sobel_15_gray.gray
convert -size 321x481 -depth 8 Boat_noisy_sobel_15_gray.gray Boat_noisy_sobel_15_gray.png
mv -f Boat_noisy_sobel_20_denoised_binary_edge_map_threshold_20.raw Boat_noisy_sobel_20_denoised_binary_edge_map_threshold_20.gray
convert -size 321x481 -depth 8 Boat_noisy_sobel_20_denoised_binary_edge_map_threshold_20.gray Boat_noisy_sobel_20_denoised_binary_edge_map_threshold_20.png
mv -f Boat_noisy_sobel_20_denoised_binary_edge_map_threshold_clean_20.raw Boat_noisy_sobel_20_denoised_binary_edge_map_threshold_clean_20.gray
convert -size 321x481 -depth 8 Boat_noisy_sobel_20_denoised_binary_edge_map_threshold_clean_20.gray Boat_noisy_sobel_20_denoised_binary_edge_map_threshold_clean_20.png
mv -f Boat_noisy_sobel_20_denoised_differentiated.raw Boat_noisy_sobel_20_denoised_differentiated.gray
convert -size 321x481 -depth 8 Boat_noisy_sobel_20_denoised_differentiated.gray Boat_noisy_sobel_20_denoised_differentiated.png
mv -f Boat_noisy_sobel_20_denoised_edge_map_no_threshold.raw Boat_noisy_sobel_20_denoised_edge_map_no_threshold.gray
convert -size 321x481 -depth 8 Boat_noisy_sobel_20_denoised_edge_map_no_threshold.gray Boat_noisy_sobel_20_denoised_edge_map_no_threshold.png
mv -f Boat_noisy_sobel_20_denoised.raw Boat_noisy_sobel_20_denoised.gray
convert -size 321x481 -depth 8 Boat_noisy_sobel_20_denoised.gray Boat_noisy_sobel_20_denoised.png
mv -f Boat_noisy_sobel_20_gray.raw Boat_noisy_sobel_20_gray.gray
convert -size 321x481 -depth 8 Boat_noisy_sobel_20_gray.gray Boat_noisy_sobel_20_gray.png
mv -f Boat_noisy_sobel_5_denoised_binary_edge_map_threshold_5.raw Boat_noisy_sobel_5_denoised_binary_edge_map_threshold_5.gray
convert -size 321x481 -depth 8 Boat_noisy_sobel_5_denoised_binary_edge_map_threshold_5.gray Boat_noisy_sobel_5_denoised_binary_edge_map_threshold_5.png
mv -f Boat_noisy_sobel_5_denoised_binary_edge_map_threshold_clean_5.raw Boat_noisy_sobel_5_denoised_binary_edge_map_threshold_clean_5.gray
convert -size 321x481 -depth 8 Boat_noisy_sobel_5_denoised_binary_edge_map_threshold_clean_5.gray Boat_noisy_sobel_5_denoised_binary_edge_map_threshold_clean_5.png
mv -f Boat_noisy_sobel_5_denoised_differentiated.raw Boat_noisy_sobel_5_denoised_differentiated.gray
convert -size 321x481 -depth 8 Boat_noisy_sobel_5_denoised_differentiated.gray Boat_noisy_sobel_5_denoised_differentiated.png
mv -f Boat_noisy_sobel_5_denoised_edge_map_no_threshold.raw Boat_noisy_sobel_5_denoised_edge_map_no_threshold.gray
convert -size 321x481 -depth 8 Boat_noisy_sobel_5_denoised_edge_map_no_threshold.gray Boat_noisy_sobel_5_denoised_edge_map_no_threshold.png
mv -f Boat_noisy_sobel_5_denoised.raw Boat_noisy_sobel_5_denoised.gray
convert -size 321x481 -depth 8 Boat_noisy_sobel_5_denoised.gray Boat_noisy_sobel_5_denoised.png
mv -f Boat_noisy_sobel_5_gray.raw Boat_noisy_sobel_5_gray.gray
convert -size 321x481 -depth 8 Boat_noisy_sobel_5_gray.gray Boat_noisy_sobel_5_gray.png

